[project]
name = "llama3-2-vision-90b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.4.7",
    "pypdf2>=3.0.1",
    "rich>=13.9.4",
    "streamlit>=1.43.2",
]
